name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
      
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write   # NPM
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Setup Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'

      - run: npm ci
        env:
          npm_config_disturl: https://electronjs.org/headers
          npm_config_target: 32.1.2
          npm_config_runtime: electron
          npm_config_build_from_source: true

      - name: Publish to NPM Registry
        run: npm publish --verbose --tag latest --provenance --access=public